import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	main: [
		"intro",
		{
			type: "category",
			label: "API",
			items: [{ type: "autogenerated", dirName: "api" }],
		},
		{
			type: "category",
			label: "Engineering",
			items: [{ type: "autogenerated", dirName: "engineering" }],
		},
	],
};

export default sidebars;
